import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Construction Copilot",
  description: "Terms of Service for Construction Copilot",
};

export default function Terms() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl prose prose-slate">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-6">
        Version 1.0 | Effective Date: November 4, 2024
      </p>

      <p className="mb-8">
        This Construction Copilot Terms of Service Agreement (&quot;Agreement&quot;) is entered into by and
        between Weigh Anchor LLC (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) and the entity or person
        (&quot;User,&quot; &quot;you,&quot; or &quot;your&quot;) accessing or using the Construction Copilot services (&quot;Services&quot;).
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">1. Definitions</h2>
        <div className="space-y-4">
          <p>
            1.1 &quot;Authority Having Jurisdiction&quot; or &quot;AHJ&quot; means the organization, office, or individual
            responsible for enforcing the requirements of a code or standard, or for approving equipment,
            materials, an installation, or a procedure.
          </p>
          <p>
            1.2 &quot;Services&quot; means the Construction Copilot platform, including scope creation tools,
            proposal review capabilities, lessons learned repository, and any associated Project Management
            Information System (PMIS) features.
          </p>
          <p>
            1.3 &quot;Content&quot; means any information, data, text, documents, specifications, plans, drawings,
            designs, or other materials uploaded to, generated by, or accessed through the Services.
          </p>
          <p>
            1.4 &quot;Professional User&quot; means any architect, engineer, contractor, project manager, or other
            construction professional using the Services.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">2. Service Description and Role</h2>
        <div className="space-y-4">
          <div>
            <p className="font-semibold">2.1 Assistance Tool Only</p>
            <p>
              Construction Copilot is an AI-powered assistance tool designed to augment and expedite 
              construction documentation and project management processes. The Services do not replace 
              professional judgment, experience, or expertise.
            </p>
          </div>
          <div>
            <p className="font-semibold">2.2 No Professional Advice</p>
            <p>
              The Services do not provide professional architectural, engineering, construction, or legal 
              advice. Any content generated through the Services requires professional review and 
              validation before use.
            </p>
          </div>
          <div>
            <p className="font-semibold">2.3 User Responsibility</p>
            <p>Users retain full responsibility for:</p>
            <ul className="list-disc pl-6">
              <li>Reviewing and validating all generated content</li>
              <li>Ensuring compliance with applicable codes, standards, and regulations</li>
              <li>Obtaining necessary approvals from relevant AHJs</li>
              <li>Professional stamps and certifications</li>
              <li>Final deliverable accuracy and completeness</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">3. Subscriptions and Access</h2>
        <div className="space-y-4">
          <div>
            <p className="font-semibold">3.1 Service Tiers</p>
            <ul className="list-disc pl-6">
              <li>Free Viewing Tier: Limited to viewing capabilities</li>
              <li>Standard Subscription ($19.99/month): Full access to current scope creation and review features</li>
              <li>Enterprise Solutions: Custom solutions for full PMIS implementation (when available)</li>
            </ul>
          </div>
          <div>
            <p className="font-semibold">3.2 Account Requirements</p>
            <ul className="list-disc pl-6">
              <li>Provide accurate registration information</li>
              <li>Maintain account security</li>
              <li>Be at least 18 years old</li>
              <li>Have authority to accept these terms on behalf of their organization (if applicable)</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">4. Data Privacy and Security</h2>
        <div className="space-y-4">
          <div>
            <p className="font-semibold">4.1 Data Protection</p>
            <p>We implement double encryption:</p>
            <ul className="list-disc pl-6">
              <li>Primary encryption within our application</li>
              <li>Secondary encryption through third-party API providers</li>
            </ul>
          </div>
          <div>
            <p className="font-semibold">4.2 No Data Selling</p>
            <p>
              We do not sell, trade, or rent user data to third parties. Our subscription model exists 
              specifically to avoid data monetization.
            </p>
          </div>
          <div>
            <p className="font-semibold">4.3 Third-Party Services</p>
            <p>We use select third-party services for:</p>
            <ul className="list-disc pl-6">
              <li>Database management (e.g., Firebase)</li>
              <li>Authentication (OAuth)</li>
              <li>AI processing (e.g., Anthropic)</li>
              <li>Other operational needs</li>
            </ul>
          </div>
          <div>
            <p className="font-semibold">4.4 Data Processing</p>
            <p>By using our Services, you acknowledge that:</p>
            <ul className="list-disc pl-6">
              <li>Data will be processed by AI models with appropriate encryption</li>
              <li>Third-party providers may have their own Terms of Service</li>
              <li>We may change service providers as needed for operational efficiency</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">5. User Content and Feedback</h2>
        <div className="space-y-4">
          <div>
            <p className="font-semibold">5.1 Content Ownership</p>
            <p>Users retain all rights to their uploaded Content.</p>
          </div>
          <div>
            <p className="font-semibold">5.2 Feedback</p>
            <p>
              Users may provide voluntary feedback for service improvement. Any provided feedback 
              becomes our property and may be used to enhance the Services.
            </p>
          </div>
          <div>
            <p className="font-semibold">5.3 Knowledge Base</p>
            <p>
              Shared knowledge is derived only from voluntary user feedback and is anonymized before 
              integration into the system.
            </p>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">6. Professional Responsibility and Liability</h2>
        <div className="space-y-4">
          <div>
            <p className="font-semibold">6.1 Professional Oversight</p>
            <p>All deliverables produced using the Services must be reviewed and approved by:</p>
            <ul className="list-disc pl-6">
              <li>Appropriate professional personnel</li>
              <li>Required authorities and stakeholders</li>
              <li>Relevant AHJ representatives</li>
            </ul>
          </div>
          <div>
            <p className="font-semibold">6.2 Liability Limitations</p>
            <ul className="list-disc pl-6">
              <li>We are not responsible for construction errors or omissions</li>
              <li>We do not assume any professional liability</li>
              <li>We are not responsible for project outcomes</li>
              <li>Users indemnify us against claims arising from use of the Services</li>
            </ul>
          </div>
          <div>
            <p className="font-semibold">6.3 Geographic Limitations</p>
            <ul className="list-disc pl-6">
              <li>Services are marketed and intended for use in the United States</li>
              <li>Users outside the USA use the Services at their own risk</li>
              <li>Compliance with local regulations is user's responsibility</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">7. Disclaimers and Warranties</h2>
        <div className="space-y-4">
          <div>
            <p className="font-semibold">7.1 Service Warranty</p>
            <p>Services are provided &quot;as is&quot; without warranty of any kind.</p>
          </div>
          <div>
            <p className="font-semibold">7.2 Generated Content</p>
            <p>We do not warrant:</p>
            <ul className="list-disc pl-6">
              <li>Accuracy of AI-generated content</li>
              <li>Fitness for any particular purpose</li>
              <li>Compliance with codes or standards</li>
              <li>Completeness of any generated materials</li>
            </ul>
          </div>
          <div>
            <p className="font-semibold">7.3 Data Security</p>
            <p>While we implement reasonable security measures:</p>
            <ul className="list-disc pl-6">
              <li>We cannot guarantee absolute data security</li>
              <li>We are not liable for data breaches or unauthorized access</li>
              <li>Users should maintain their own data backups</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">8. Limitation of Liability</h2>
        <div className="space-y-4">
          <div>
            <p className="font-semibold">8.1 Liability Cap</p>
            <p>
              Our liability shall be limited to the amount paid by user for Services in the 12 months 
              preceding any claim.
            </p>
          </div>
          <div>
            <p className="font-semibold">8.2 Excluded Damages</p>
            <p>We are not liable for:</p>
            <ul className="list-disc pl-6">
              <li>Construction errors or defects</li>
              <li>Professional liability claims</li>
              <li>Regulatory compliance issues</li>
              <li>Consequential or indirect damages</li>
              <li>Lost profits or business opportunities</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">9. Termination</h2>
        <div className="space-y-4">
          <div>
            <p className="font-semibold">9.1 Termination Rights</p>
            <p>Either party may terminate:</p>
            <ul className="list-disc pl-6">
              <li>At will with 30 days' notice</li>
              <li>Immediately for material breach</li>
              <li>Immediately for professional misconduct</li>
            </ul>
          </div>
          <div>
            <p className="font-semibold">9.2 Post-Termination</p>
            <p>Upon termination:</p>
            <ul className="list-disc pl-6">
              <li>Access to Services will cease</li>
              <li>Users may export their data within 30 days</li>
              <li>Users retain responsibility for all prior use</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">10. Governing Law and Jurisdiction</h2>
        <div className="space-y-4">
          <p>
            10.1 This Agreement is governed by the laws of the United States and the State of 
            Washington.
          </p>
          <p>
            10.2 Any disputes shall be resolved in the federal or state courts located in Washington 
            State.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">11. Changes to Terms</h2>
        <div className="space-y-4">
          <p>11.1 We may modify these terms at any time with notice to users.</p>
          <p>11.2 Continued use after modifications constitutes acceptance of updated terms.</p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">12. Contact Information</h2>
        <p>
          12.1 For questions about these terms, contact: <span className="font-semibold">info@weighanchor.com</span>
        </p>
      </section>

      <p className="mt-8">
        By using the Services, you acknowledge that you have read, understood, and agree to be bound 
        by these Terms of Service.
      </p>

      <p className="text-sm text-muted-foreground mt-8">
        Last updated: November 4, 2024
      </p>
    </div>
  );
}